# Python Libraries For Data Science


In [1]:
import numpy as np



In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
arr_2d=np.array([[1,2,3],[2,3,4]])
arr_2d

array([[1, 2, 3],
       [2, 3, 4]])

In [7]:
type(arr_2d)

numpy.ndarray

In [8]:
arr_3d=np.array([[1,2],[2,5],[3,6]])
arr_3d

array([[1, 2],
       [2, 5],
       [3, 6]])

In [13]:
l1=[1,2,3,4]
l2=[]
for i in l1:
    l2.append(i**2)
l2

[1, 4, 9, 16]

In [14]:
res=lambda x:x**2
list(map(res,l1))

[1, 4, 9, 16]

In [17]:
[i**2 for i in l1]

[1, 4, 9, 16]

In [20]:
s1=np.array([1,2,3,4])
print(s1**2)

[ 1  4  9 16]


In [21]:
s2=np.array([3,4,5,6])
s1+s2

array([ 4,  6,  8, 10])

In [24]:
s2[1]

4

In [29]:
print(arr_2d)
arr_2d[1][1]

[[1 2 3]
 [2 3 4]]


3

In [31]:
%time #time taken to execute a code
s1/s2


Wall time: 0 ns


array([0.33333333, 0.5       , 0.6       , 0.66666667])

In [35]:
a=np.arange(0,11,2) #a=np.array(range(0,11,2)) gives the same result
a

array([ 0,  2,  4,  6,  8, 10])

In [41]:
a3=np.linspace(1,10,50)# divides 1 to 10 numbers into specipied parts(here 50)
a3

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [43]:
range(1.5,10.5)

TypeError: 'float' object cannot be interpreted as an integer

In [49]:
a2=np.linspace(1.5,10.5,5)#linspace support float values
a2

array([ 1.5 ,  3.75,  6.  ,  8.25, 10.5 ])

In [51]:
type(a2[2])

numpy.float64

In [52]:
print(arr_3d)
arr_3d.reshape(2,3)

[[1 2]
 [2 5]
 [3 6]]


array([[1, 2, 2],
       [5, 3, 6]])

In [62]:
arr_3d.reshape(6,-1)# -1 is given only when no.of either rows or columns are negotiated

array([[1],
       [2],
       [2],
       [5],
       [3],
       [6]])

In [66]:
a=np.array([[[1,2,3],[4,5,6]],[[3,4,5],[5,6,7]]])
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 4, 5],
        [5, 6, 7]]])

In [68]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

In [70]:
d=np.arange(1,500,9)
d

array([  1,  10,  19,  28,  37,  46,  55,  64,  73,  82,  91, 100, 109,
       118, 127, 136, 145, 154, 163, 172, 181, 190, 199, 208, 217, 226,
       235, 244, 253, 262, 271, 280, 289, 298, 307, 316, 325, 334, 343,
       352, 361, 370, 379, 388, 397, 406, 415, 424, 433, 442, 451, 460,
       469, 478, 487, 496])

In [71]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [72]:
np.ones((10,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [73]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [78]:
np.eye(4,dtype=int)# identity matrix

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [87]:
np.eye(4,k=2)# k value indicates to print "1" leaving 2 places from corner represents

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [93]:
print(arr_2d)
arr_2d.T

[[1 2 3]
 [2 3 4]]


array([[1, 2],
       [2, 3],
       [3, 4]])

In [95]:
np.random.random((2,10))

array([[0.24998005, 0.49875216, 0.34898054, 0.62107433, 0.09482904,
        0.7199763 , 0.59550203, 0.22652193, 0.3860593 , 0.34314577],
       [0.60697102, 0.74462686, 0.47144395, 0.76413014, 0.81129833,
        0.63754293, 0.90812549, 0.77310987, 0.29273344, 0.13683748]])

In [98]:
f=np.random.randint(25,100,(2,10))
f

array([[99, 37, 32, 75, 66, 61, 56, 51, 43, 91],
       [83, 92, 42, 92, 63, 65, 75, 92, 66, 26]])

In [99]:
f.shape

(2, 10)

In [108]:
f[1:]#slices the first row

array([[83, 92, 42, 92, 63, 65, 75, 92, 66, 26]])

In [112]:
f[1,[2,3]]#accesssing 2nd and 3rd element in row 1

array([42, 92])

In [113]:
np.sqrt(f)

array([[9.94987437, 6.08276253, 5.65685425, 8.66025404, 8.1240384 ,
        7.81024968, 7.48331477, 7.14142843, 6.55743852, 9.53939201],
       [9.11043358, 9.59166305, 6.4807407 , 9.59166305, 7.93725393,
        8.06225775, 8.66025404, 9.59166305, 8.1240384 , 5.09901951]])

In [114]:
np.sin(a)

array([[[ 0.84147098,  0.90929743,  0.14112001],
        [-0.7568025 , -0.95892427, -0.2794155 ]],

       [[ 0.14112001, -0.7568025 , -0.95892427],
        [-0.95892427, -0.2794155 ,  0.6569866 ]]])

In [115]:
np.log(a)

array([[[0.        , 0.69314718, 1.09861229],
        [1.38629436, 1.60943791, 1.79175947]],

       [[1.09861229, 1.38629436, 1.60943791],
        [1.60943791, 1.79175947, 1.94591015]]])

In [116]:
np.exp(f)

array([[9.88903032e+42, 1.17191424e+16, 7.89629602e+13, 3.73324200e+32,
        4.60718663e+28, 3.10429794e+26, 2.09165950e+24, 1.40934908e+22,
        4.72783947e+18, 3.31740010e+39],
       [1.11286375e+36, 9.01762841e+39, 1.73927494e+18, 9.01762841e+39,
        2.29378316e+27, 1.69488924e+28, 3.73324200e+32, 9.01762841e+39,
        4.60718663e+28, 1.95729609e+11]])

In [120]:
a=np.array([[1,2],[1,2]])
np.linalg.det(a)

0.0

In [121]:
np.linalg.eig(a)

(array([0., 3.]), array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

In [124]:
a

array([[1, 2],
       [1, 2]])

In [126]:
np.full((3,3),10)# 10 is the filling number

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [128]:
a.flattens()

array([1, 2, 1, 2])

In [130]:
np.tile(a,2)

array([[1, 2, 1, 2],
       [1, 2, 1, 2]])

In [132]:
b=np.array([[1,2,3],[1,2,3],[1,2,3]])
print(b)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [134]:
b.size

9

In [136]:
b.shape

(3, 3)

In [137]:
import math

In [141]:
math.pi#package.attribute

3.141592653589793

In [140]:
math.pow(2,3)#package.function()

8.0

In [142]:
#doc.scipy.org/doc(numpy and scipy document)